-- SELECT ALL
SELECT * FROM sales;

-- FIND ALL SALES WITH VOLUME > 1000
SELECT * 
FROM sales
WHERE volume > 1000;

-- FIND TOP 10 SALES
SELECT * 
FROM sales
ORDER BY volume DESC
LIMIT 10;

-- FIND BOTTOM 10 SALES
SELECT * 
FROM sales
ORDER BY volume ASC
LIMIT 10;

-- FIND ALL RECURRING SALES
SELECT * 
FROM sales
WHERE is_recurring IS TRUE;

-- FIND DISPUTED SALES WITH VOLUME > 5000
SELECT * 
FROM sales
WHERE is_disputed IS TRUE AND volume > 5000;

-- FIND ALL SALES CREATED BETWEEN TWO DATES
/* SELECT * 
FROM sales
WHERE date_created BETWEEN('01-01-2022', CURRENT_DATE); */

-- FIND ALL SALES FULFILLED <= 5 DAYS AFTER CREATION DATE
/* SELECT * 
FROM sales
WHERE date_fulfilled - date_created <= 5; */

-- GET DISTINCT CUSTOMER NAMES
SELECT DISTINCT customer_name
FROM sales;

-- GET DISTINCT PRODUCT NAMES
SELECT DISTINCT product_name
FROM sales;